scenario_cfg:
  dataset_name: MMBench
  base_data_path: ../data/MMBench
  ppl_cfg: 
    content_only: False
  split: dev
  hint: True
  option_map: ''

eval_cfg:
  instruction_cfg: 
    query_type: query_pool
    prompt_assigned_ids: 1 # (kosmos: 5) (default: 1) 
    template_assigned_ids: 1 # (kosmos: 0) (default: 1) 
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 6
    CoT: True
    max_new_tokens: 256
  metric_cfg:
    metric_type: Instruct_Follow