scenario_cfg:
  dataset_name: MMBench
  base_data_path: ../data/MMBench
  ppl_cfg: 
    content_only: False
  split: dev
  hint: True
  generative: True

eval_cfg:
  instruction_cfg: 
    query_type: query_pool
    query_assigned_ids: 0
    template_assigned_ids: 0
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 4
    CoT: True
    max_new_tokens: 256
  metric_cfg:
    metric_type: basic