scenario_cfg:
  dataset_name: VOC2012
  base_data_path: ../data/LAMM/2D_Benchmark

eval_cfg:
  instruction_cfg:
    query_type: multiturn
  inferencer_cfg:
    inferencer_type: Det
    max_new_tokens: 512
    batch_size: 16
  metric_cfg:
    metric_type: basic