model_name: Octavius_2d
stage: 2
octavius_modality: ['signal']

llm_ckpt_path: /data/xiaochen/FedMFM/MMedLM2/
# delta_ckpt_path: ../ckpt/octavius_2d_e4_bs64_ous_4/pytorch_model.pt
# delta_ckpt_path: /data/xiaochen/FedMFM/ckpt/ours_fedprox_multi/5/pytorch_model.pt
# delta_ckpt_path: "/data/xiaochen/FedMFM/ckpt/ours_fedprox_multi/5/pytorch_model.pt"
delta_ckpt_path: "/data/xiaochen/FedMFM/ckpt/lora_fedavg_multi/pytorch_model_ep5.pt"
# delta_ckpt_path: /data/xiaochen/FedMFM/ckpt/ours_fedprox_multi/pytorch_model_ep7.pt

encoder_pretrain: clip
vision_feature_type: local
# vision_output_layer: -2
num_vision_token: 198

# peft and lora
peft_type: moe_lora
moe_lora_num_experts: 12
moe_gate_mode: top2_gate
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
# lora_target_modules: ['q_proj', 'k_proj', 'v_proj', 'o_proj']
lora_target_modules: ['wqkv', 'wo', 'w1', 'w2', 'w3', 'output']

# pcl modality
num_query_rsp_3d: 16
hidden_size_rsp_3d: 768
num_layers_rsp_3d: 1
num_heads_rsp_3d: 8

max_tgt_len: 100
conv_mode: simple
